//! Deterministic repository-controlled Agent Skill generation.

use std::fs;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;

use clap::CommandFactory;

use crate::cli::{Cli, GenerateSkillsArgs};
use crate::error::CliError;

const SKILL: &str = r#"---
name: graduate
description: Configure Jira Cloud with Graduate. Use when an agent needs to inspect Graduate's CLI contract or establish its Jira connection.
---

# Graduate

Graduate is a Jira Cloud CLI with explicit commands, like Drag. Run `gd --help`
before constructing a command dynamically.

## Configure Jira

Interactive login verifies Jira before saving:

```sh
gd login
```

For automation, provide `ATLASSIAN_HOST`, `ATLASSIAN_EMAIL`, and
`ATLASSIAN_TOKEN`, then run `gd login --from-env`. Use `--dry-run` before
saving. Dry-run networking requires explicit `--verify`. Never print or copy
the token from environment variables or `~/.graduate/config.json`.

Interactive login requires terminal-capable stdin and stderr. Use Tab and
Shift-Tab to move, Enter to continue, Escape to go back or cancel, and Ctrl-C
to cancel from any stage.
"#;

const INDEX: &str = r#"# Agent Skills

> Generated by `gd generate-skills`. Do not edit manually.

| Skill | Description |
|---|---|
| [`graduate`](../skills/graduate/SKILL.md) | Configure Graduate and inspect its Jira CLI contract. |
"#;

pub(crate) fn run(args: &GenerateSkillsArgs) -> Result<(), CliError> {
    let skill_path = args.output_dir.join("graduate").join("SKILL.md");
    let skill = format!(
        "{SKILL}\n## Current command contract\n\n```text\n{}```\n",
        Cli::command().render_long_help()
    );
    let files = [
        GeneratedFile {
            path: &skill_path,
            content: &skill,
        },
        GeneratedFile {
            path: Path::new("docs/skills.md"),
            content: INDEX,
        },
    ];
    write_generated(&files, args.force)?;
    println!("Generated {}", skill_path.display());
    Ok(())
}

struct GeneratedFile<'a> {
    path: &'a Path,
    content: &'a str,
}

fn write_generated(files: &[GeneratedFile<'_>], force: bool) -> Result<(), CliError> {
    if !force {
        for file in files {
            if file.path.exists() {
                return Err(CliError::GeneratedFileExists(file.path.to_path_buf()));
            }
        }
    }
    for file in files {
        if let Some(parent) = file.path.parent() {
            fs::create_dir_all(parent)?;
        }
    }
    for file in files {
        if force {
            fs::write(file.path, file.content)?;
        } else {
            let mut destination = OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(file.path)?;
            destination.write_all(file.content.as_bytes())?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn existing_destination_is_rejected_before_any_file_is_written(
    ) -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let skill = directory.path().join("skills/graduate/SKILL.md");
        let index = directory.path().join("docs/skills.md");
        let parent = index.parent().ok_or("index has no parent")?;
        fs::create_dir_all(parent)?;
        fs::write(&index, "existing index")?;
        let files = [
            GeneratedFile {
                path: &skill,
                content: "skill",
            },
            GeneratedFile {
                path: &index,
                content: "index",
            },
        ];

        let result = write_generated(&files, false);

        assert!(matches!(result, Err(CliError::GeneratedFileExists(_))));
        assert!(!skill.exists());
        assert_eq!(fs::read_to_string(index)?, "existing index");
        Ok(())
    }
}
