name: Feature request
description: Propose an improvement
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed CLI experience
      description: Show the command and expected output when possible.
      render: shell
    validations:
      required: true
